---

# Get helm install script
- name: git clone repo
  git:
    repo: https://github.com/mugithi/openstack-helm.git
    dest: /openstack-helm/
    force: yes

# Make file executable
- name: Make file executable
  file:
    path: /openstack-helm/setup_helm.sh
    owner: ubuntu
    group: ubuntu 
    mode: 0755

# Make file executable
- name: Make file executable
  file:
    path: /openstack-helm/make_helm.sh
    owner: ubuntu
    group: ubuntu
    mode: 0755

# Make file executable
- name: Make file executable
  file:
    path: /openstack-helm/label_node.sh
    owner: ubuntu
    group: ubuntu
    mode: 0755

# Make file executable
- name: Make file executable
  file:
    path: /openstack-helm/install_ceph.sh
    owner: ubuntu
    group: ubuntu
    mode: 0755

# Install Openstack on Kubernetes
- name: Install helm chart 
  command: /openstack-helm/setup_helm.sh
  become: true 
  ignore_errors: yes

# Install Openstack on Kubernetes
- name: Install helm chart
  command: /openstack-helm/make_helm.sh
  become: true
  ignore_errors: yes

# Install Openstack on Kubernetes
- name: Install helm chart
  command: /openstack-helm/label_node.sh
  become: true
  ignore_errors: yes

# Install Openstack on Kubernetes
- name: Install helm chart
  command: /openstack-helm/install_ceph.sh
  become: true
  ignore_errors: yes

